# Generated by Django 4.2.6 on 2023-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("discount", models.FloatField()),
            ],
        ),
    ]
